.TH LINKSCHEME 1
.SH NAME
linkscheme \- links ELK Scheme interpreter with your application
.SH SYNOPSIS
.B linkscheme
.I "output-file [object-file ...]"
.SH "DESCRIPTION"
This script creates an interpreter that is linked statically with your
extensions and/or application-specific object files (usually on platforms
that don't support incremental linking).

The first argument is the executable to be created, the remaining
arguments are the object files and optional libraries.
.SH AUTHOR
This manual page was written by E. Zanardi,
for the Debian GNU/Linux system.
