.TH MAKEDL 1
.SH NAME
makedl \- create dynamically loadable extension
.SH SYNOPSIS
.B makedl
.I "output-file object-file ... [library ...]"
.SH "DESCRIPTION"
.B makedl
can be used to link one dynamically loadable extension (an object file); or
combine several object files into one dynamically loadable extension
and resolve against libraries.
.SH AUTHOR
This manual page was written by E. Zanardi,
for the Debian GNU/Linux system.
